### ISSUE TITLE
ItemsAdder wrong text in plugin info

### ISSUE THREAD

**Issue by LoneDev6** [OsipXD/MimicAPI#39]
Hello!
This text is wrong https://www.spigotmc.org/resources/mimic.82515/

![image](https://user-images.githubusercontent.com/27242001/211323708-4f26d806-1a83-441b-8c53-8fcc4f08f2a9.png)

Should be:
`- ItemsAdder (ia:[namespace]:[id])`

Here is the correct tutorial:
https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/mimic

**Comment by osipxd** [comment]
Thank you, fixed
